jenkins-infra/jenkins-io-components

- .github/workflows/release.yml
- package-lock.json
- package.json
- rollup.config.js
- src/jio-searchbox.ts
- tsconfig.json
chore: Migrate rollup to produce es (modern javascript). I had esm and ejs which were not correct, rollup just ignored those values
fix: navbar loads docsearch from bundle (on demand) which is way easier to detect when finished loading.
> Migrate to proper esbuild, and upgrade algolia

- .gitignore
- src/jio-navbar.ts
Let's use the up-to-date website URL of tekton, found in various tekton docs itself.
> Update tekton URL

- rollup.config.js
- src/jio-locale.ts
instead of loading `./generated/locales/${locale}` which doesn't seem to translate properly, just hardcode the locale options for now and let them get loaded
> fix: Hardcode locale

- package.json
- src/jio-searchbox.ts
Apparently requesting english only results messed with all the other ranking realted search settings, so for now (since we only have english only results), just use default search settings
> fix: Search wasn't returning items in priority order

- .gitignore
- src/generated/locales/en.ts
- src/generated/locales/es-ES.ts
- src/generated/locales/fr-CA.ts
- src/jio-navbar.ts
- xliff/en.xlf
- xliff/es-ES.xlf
- xliff/fr-CA.xlf
The chinese website remains almost unmodified since 2019 and there are ongoing efforts to detach it from our resources. 
I would like to remove it from the navbar component. Not only for the reason that it's in a sunset state, but also to draw focus on jenkins.io and prevent future misguidance of newbie contributors and GSoC students who want to contribute.
> Remove references to sunset chinese website

- src/jio-footer.ts
- src/jio-report-a-problem.ts
- src/stories/Footer.stories.ts
- src/stories/ReportAProblem.stories.ts
This PR adapts the GitHub issue form syntax. `problem` matches the unique ID, I gave the issue field this information should be filled in to.
The default body can be removed by now because I incorporated it into the issue form default.
This PR depends on the following jenkins.io PR: https://github.com/jenkins-infra/jenkins.io/pull/6086
> fix(reportaproblem): Switch to GH issue form syntax

- src/jio-navbar.ts
To prevent making the documentation dropdown menu of the navbar even longer, two sub-menus, `Guided Tour` and `More Tutorials`, now there, need to be removed. 
For more details please refer to the following PR: https://github.com/jenkins-infra/jenkins-io-components/pull/79
> feat: Removed sub sections of `Tutorial` from documentation dropdown

- src/jio-navbar.ts
I believe adding stories.jenkins.io in a prominent location like the navbar draws more attention to our user stories.
These success stories are a major component for the Jenkins community and should be placed in a more prominent location.
Currently, they aren't displayed in any prominent location.
> feat: Add stories.jenkins.io to navbar

- src/jio-footer.ts
A minor change replacing the banner with the SVG one, to ensure the image is reactive on different devices, instead of being blurry.
Before:
After:
> feat: Replace CC by-sa banner with SVG

- src/jio-navbar.ts
The sidepanel sections of https://www.jenkins.io/security/ and related pages do not make a great selection of menu entries.
This essentially replaces those with the main content areas of https://www.jenkins.io/security/ (security advisories and vulnerability reporting), which we expect are far more relevant for most visitors.
Untested.
CC @Wadeck
> refactor: Add links to advisories, remove links to less relevant pages

- src/jio-locale.ts
This is not an error and should not be logged as such.
> chore: Lower log level of "locale not found" message

- rollup.config.js
- src/jio-navbar.css
- src/jio-navbar.ts
- src/stories/Navbar.stories.ts
Adds theme attribute that can be either light (default), dark or auto. That should allow adding dark mode to plugin site before we add it to the others and allow adding a color theme toggle to the page in the future.
> feat: Add dark mode support

- src/jio-footer.ts
This PR is to suggest changing the Twitter text at in the footer to be "X (formerly Twitter)" so that we stay current with naming/branding.
This is in response to discussion being had during the [January 11 Advocacy & Outreach meeting](https://community.jenkins.io/t/advocacy-outreach-sig-meeting-2024-01-11/11739)
Several other projects are still using _just_ Twitter, but the CD Foundation is using the X logo, so we want to try and align with them as best we can.
If there are any thoughts or feelings against this idea, it would be great to see other examples of how this is being addressed.
> feat: updating twitter to x (formerly twitter)

- src/jio-footer.ts
this **PR** contains correcting the direction of footer element which is 'Code of Conduct' to direct to the right page
a workaround was created in jenkins.io repository which is redirecting from `'/conduct'` to `'/project/conduct' `
but this **PR** solves the problem 
issue related: #132
> fix: Correct link direction in footer - code of conduct

- CONTRIBUTING.md
this PR addressing [issue#105](https://github.com/jenkins-infra/jenkins-io-components/issues/105)
this is a proposed contribution guide that we can refer to in the README to insure consistency
> docs: Add CONTRIBUTING.md to follow Conventional Commits

- src/jio-navbar.css
Fixes https://github.com/jenkins-infra/contributor-spotlight/issues/208
1. Addressed issue created in https://github.com/jenkins-infra/contributor-spotlight/issues/208
2. Previously the dropdown menu was on left side in smaller screen across all Jenkins website
3. Fixed issue and made the tooltip positioning responsive for every size of the screen
4. Attachment:
https://github.com/user-attachments/assets/2628a9af-7167-4d3c-b31f-081caec4b082
> fix: correct tooltip position for dropdown menu of smaller screens

- src/jio-footer.ts
This PR adds a link to the Jenkins Infra Stats website that is being revamped as part of GSoC 2024.
closes #147 
ref:
- https://github.com/jenkins-infra/stats.jenkins.io/issues/88
@krisstern @gounthar
> feat: add link to infra stats page in footer

- src/jio-navbar-link.ts
- src/jio-navbar.css
Added hover effect to Navbar links.
**Before:**
**After:**
Fixes #144
> feat: Add hover effect to Navbar links

- src/jio-footer.ts
we were having the "Report infra issue" in all pages of jenkins.io which wasnt the intended changes..We should have it only in the download and download/mirror pages..
This PR tries to resolve that.
> fix: correct `report-infra-issue` to show only on download and download/mirror pages

- src/jio-footer.ts
Follow up of #161 to show the `report-infra-issue` in the download and download/mirror page
> fix: report-infra-issue to load in download and download/mirrors/ pages

- src/jio-footer.ts
From the [Advocacy & Outreach SIG meeting on May 15](https://community.jenkins.io/t/2025-may-15-advocacy-outreach-sig-meeting/31270/2), CD Foundation has asked that we include their copyright/terms of use information on the jenkins.io site. I have added the requested text and links to the footer of the page so that it is present in all areas.
Storybook preview:
> feat: Add CDF copyright text and links
